### PR TITLE
Feat : Fix validation library and update documentation

### PR DESCRIPTION
**Pull request by Melvynx**
Fixes: Error in context 
Add: Adapters
Update: Documentation

## Proposed Changes

- Pass `TContext` for each method
- Fix validation library
- Add tests for types given by validation library

## Use the same API as `next-safe-action`

The library you previously used to validate data was not working correctly on my side. All types are always `undefined` and I am unable to get the correct types.

I find the approach of `next-safe-action` very good and I think it's a great improvement to follow its syntax.

---

If you accept, I would be happy to contribute to help you improve the repository.

### CODE REVIEW

**Comment by Melvynx** [comment]
Review by @richardsolomou

**Comment by Melvynx** [comment]
@richardsolomou don't hesitate to change anything

**Comment by Melvynx** [comment]
@richardsolomou ?

**Comment by richardsolomou** [comment]
Hey, thanks a lot for the PR, going through and testing it now :)

**Comment by richardsolomou** [comment]
@Melvynx ?

**Pull request closed without merging**
